# Networking config for mycloud-nixos-2.
# Public IP: 37.27.193.229 (Hetzner, managed via infra/machines.tf)
# Tailscale IP: 100.64.0.10 (assigned by headscale)
{ lib, ... }:
let
  tailscaleIp = "100.64.0.10";
in {
  networking = {
    hostName = "mycloud-nixos-2";
    firewall = {
      allowedTCPPorts = [
        80
        443
        22000  # syncthing
      ];
      allowedUDPPorts = [ 22000 21027 ];  # syncthing discovery
    };

    # Static networking (generated by nixos-infect)
    nameservers = [
      "2a01:4ff:ff00::add:2"
      "2a01:4ff:ff00::add:1"
      "185.12.64.1"
    ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces.eth0 = {
      ipv4.addresses = [ { address = "37.27.193.229"; prefixLength = 32; } ];
      ipv6.addresses = [
        { address = "2a01:4f9:c012:ef00::1"; prefixLength = 64; }
        { address = "fe80::9400:3ff:fe92:42e7"; prefixLength = 64; }
      ];
      ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
      ipv6.routes = [ { address = "fe80::1"; prefixLength = 128; } ];
    };
  };

  services.udev.extraRules = ''
    ATTR{address}=="96:00:03:92:42:e7", NAME="eth0"
  '';

  # -- Headscale --
  services.headscale = {
    enable = true;
    port = 8083;
    settings = {
      serverUrl = "https://headscale.romeov.me";
      noise.private_key_path = "/var/lib/headscale/noise_private.key";
      policy = {
        path = "/etc/headscale/tailnet_policy_file.json";
        mode = "file";
      };
      dns = {
        base_domain = "mycloud";
        override_local_dns = false;
        extra_records = map (name: {
          inherit name;
          type = "A";
          value = tailscaleIp;
        }) [
          "storage.mycloud"
          "freshrss.mycloud"
          "blog.mycloud"
          "immich.mycloud"
          "openclaw.mycloud"
        ];
      };
    };
  };
  environment.etc."headscale/tailnet_policy_file.json".text = builtins.toJSON {
    acls = [{ action = "accept"; src = ["*"]; dst = ["*:*"]; }];
    tagOwners = { "tag:bazzite" = ["romeo@"]; };
    ssh = [
      {
        action = "accept";
        src = ["autogroup:member"];
        dst = ["autogroup:self"];
        users = ["romeo" "root"];
      }
      {
        action = "accept";
        src = ["autogroup:member"];
        dst = ["tag:bazzite"];
        users = ["merel"];
      }
      {
        action = "accept";
        src = ["romeo@"];
        dst = ["tag:bazzite"];
        users = ["romeo" "root"];
      }
    ];
  };
  systemd.services.headscale.serviceConfig.TimeoutStopSec = "15s";
}
